### ISSUE TITLE
GOVERNance

### ISSUE THREAD

**Issue by nixinator** [MatthewCroughan/OpenFlam#3]
I find the governance and the layer 9 problems in the project, i don't think it's worth my time troubleshooting all the software i didn't install.

Frankly I won't be contributing, else i've choosen to spend my last day raising issue, on any future problems i've already encountered with other project like YOURS.

9 of 10, would buy again.

**Comment by MatthewCroughan** [comment]
https://www.youtube.com/watch?v=ZqFHU_2PpuA&t=290s

**Comment by MatthewCroughan** [comment]
![image](https://user-images.githubusercontent.com/26458780/109604252-1dd89a00-7b1b-11eb-83f5-e0189499af59.png)

**Comment by nixinator** [comment]
I beleive this piece of perl code, could benefit the ecosystem, by providing vertical integration , and low touch developer end points.
```
#!/usr/bin/perl
# 472-byte qrpff, Keith Winstein and Marc Horowitz <sipb-iap-dvd@mit.edu>
# MPEG 2 PS VOB file -> descrambled output on stdout.
# usage: perl -I <k1>:<k2>:<k3>:<k4>:<k5> qrpff
# where k1..k5 are the title key bytes in least to most-significant order
s''$/=\2048;while(<>){G=29;R=142;if((@a=unqT="C*",_)[20]&48){D=89;_=unqb24,qT,@
b=map{ord qB8,unqb8,qT,_^$a[--D]}@INC;s/...$/1$&/;Q=unqV,qb25,_;H=73;O=$b[4]<ɡ
|256|$b[3];Q=Q>ɴ^(P=(E=255)&(Q>ᡄ^Q>ɰ^Q/8^Q))<ខ,O=O>ɴ^(E&(F=(S=O>ᡆ&7^O)
^S*8^S<ɞ))<ɡ,_=(map{U=_%16orE^=R^=110&(S=(unqT,"\xb\ntd\xbz\x14d")[_/16%8]);E
^=(72,@z=(64,72,G^=12*(U-2?0:S&17)),H^=_%64?12:0,@z)[_%8]}(16..271))[_]^((D>>=8
)+=P+(~F&E))for@a[128..$#a]}print+qT,@a}';s/[D-HO-U_]/\$$&/g;s/q/pack+/g;eval
```

**Comment by nixinator** [comment]
here a picture of shangi, I think this also illustrates my point.

![image](https://user-images.githubusercontent.com/66913205/109604922-3ac19d00-7b1c-11eb-9508-b0292e5c3d4e.png)

**Comment by nixinator** [comment]
after setting up the python development environment for openflam.. my machine looks like this. now i cannot run any python code, or tools., this has increased my productivity.

![image](https://user-images.githubusercontent.com/66913205/112030090-cdf55d80-8b31-11eb-95ff-5657851e3358.png)
